import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import { Abel } from "next/font/google";
import { cn } from "@/lib/utils";
import Navbar from "@/components/ui/navbar";
import ThemeProvider from "@/components/ui/themeProvider";

const geist = Abel({ subsets: ["latin"], weight: "400" });

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={cn("font-sans", geist.className)}
      suppressHydrationWarning
    >
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <ThemeProvider attribute="class" defaultTheme="system" enableSystem disableTransitionOnChange>
          <Navbar />

          {children}
        </ThemeProvider>
      </body>
    </html>
  );
}
